### ISSUE TITLE
Unable to build the project using gulp. 

### ISSUE THREAD

**Issue by ksgupta** [AlexDisler/ionic-lock-screen#9]
Thanks for this amazing module. :)

I wanted to add the functionality to dynamically check the validity of the code with server and resolve/reject the operation accordingly. 

I made the changes on my local in the src folder, but when I am trying to build the project with gulp, it is giving me the error as below. I have no prior experience with gulp, but this should be a standard procedure I believe.

Please share if you have any documents on how to build the project.

Thanks again!

Command and error:

ionic-lock-screen$ gulp build
[02:24:29] Requiring external module babel-register
/work/github/ionic-lock-screen/gulpfile.babel.js:1
(function (exports, require, module, __filename, __dirname) { import concat from 'gulp-concat';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at loader (/work/github/ionic-lock-screen/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/work/github/ionic-lock-screen/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:193:16)

**Comment by AlexDisler** [comment]
Hi,

I think it's happening because this project uses an older version of gulp and babel.

You can try to copy the ```.babelrc``` and babel/gulp versions from this project https://github.com/AlexDisler/cordova-plugin-inapppurchase - it has a similar setup but with the newer versions.

**Comment by remib** [comment]
Make sure you run npm install on the directory first.
